image:
  file: .gitpod.Dockerfile
tasks:
  - name: npm
    command: echo "Rodando command da task npm"
    init: npm install npm@latest -g
  - name: Mocha
    init: npm install -g mocha
  - name: Docker
    init: docker start postgres adminer mongodb mongoclient
