image:
  file: .gitpod.Dockerfile
tasks:
  - name: npm
    init: npm install npm@latest -g
  - name: mocha
    init: npm install -g mocha
  - name: docker-postgres
    init: echo 'running docker postgres'
    command: echo 'startinh docker postgres'