image:
  file: .gitpod.Dockerfile
tasks:
  - name: npm
    init: npm install npm@latest -g
  - name: mocha
    init: npm install -g mocha
  - name: docker-postgres
    init: >
      docker run 
      --name postgres 
      -e POSTGRES_USER=admin 
      -e POSTGRES_PASSWORD=admin 
      -e POSTGRES_DB=heroes 
      -p 5432:5432 
      -d 
      postgres &&
      gp sync-done postgres
    command: docker start postgres
  - name: docker-adminer
    init: >
      gp sync-await postgres &&
      docker run 
      --name adminer 
      -p 8080:8080 
      --link postgres:postgres 
      -d 
      adminer
    command: docker start adminer
  - name: docker-mongodb
    init: >
      docker run 
      --name mongodb 
      -p 27017:27017 
      -e MONGO_INITDB_ROOT_USERNAME=admin 
      -e MONGO_INITDB_ROOT_PASSWORD=senhaadmin 
      -d 
      mongo:4
    command: docker start mongodb
  - name: create-user-mongodb
    init: >
      docker exec -it mongodb 
      mongo --host localhost -u admin -p senhaadmin --authenticationDatabase admin 
      --eval "db.getSiblingDB('heroes').createUser({user: 'gabrielsousa', pwd: 'admin', roles: [{role: 'readWrite', db: 'heroes'}]})"
  - name: docker-mongoclient
    init: >
      docker run
      --name mongoclient 
      -p 3000:3000 
      --link mongodb:mongodb 
      -d 
      mongoclient/mongoclient
    command: docker start mongoclient
